import type { Metadata } from "next";
import { headers } from "next/headers";
import Header from "../components/atoms/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headersObj = await headers();
  const cookies = headersObj.get("cookie");

  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        {/* <Provider cookies={cookies}> */}
        <div className="flex flex-col min-h-screen w-full">
          <Header />
          <main className="flex-1 overflow-y-auto">{children}</main>
        </div>
        {/* </Provider> */}
      </body>
    </html>
  );
}
