[package]
name = "indexer"
version = "0.1.0"
edition = "2024"

[dependencies]
alloy = { version = "1.0.37", features = ["full"] }
colored = "3.0.0"
config = { version = "0.15.18", features = ["toml"] }
dotenv = "0.15.0"
eyre = "0.6.12"
futures-util = "0.3.31"
num-bigint = "0.4.6"
serde = "1.0.228"
sqlx = { version = "0.8.6", features = ["runtime-tokio", "postgres", "runtime-tokio-rustls", "macros"] }
throw = "0.1.7"
tokio = { version = "1.47.1", features = ["full"] }
toml = "0.9.7"
database = { workspace = true }
