[package]
name = "indexer"
version = "0.1.0"
edition = "2021"

[lib]
name = "indexer"
path = "src/lib.rs"

[[bin]]
name = "indexer"
path = "src/main.rs"

[dependencies]
config = { version = "0.15.18", features = ["toml"] }
dotenv = "0.15.0"
eyre = "0.6.12"
futures-util = "0.3.31"
num-bigint = "0.4.6"
serde = "1.0.228"
sqlx = { version = "0.8.6", features = ["runtime-tokio", "postgres", "runtime-tokio-rustls", "macros"] }
throw = "0.1.7"
tokio = { version = "1.47.1", features = ["full"] }
toml = "0.9.7"
database = { workspace = true }
tracing-subscriber = { version = "0.3.20", features = ["env-filter"] }
anyhow = "1.0.100"
alloy = { version = "1.0.41", features = ["network", "providers"] }
features = "0.10.0"
alloy-provider = { version = "1.0.41", features = ["ws"] }
alloy-signer = "1.0.41"
alloy-signer-local = "1.0.41"
alloy-sol-macro = "1.4.1"
alloy-contract = "1.0.41"
tracing = "0.1.41"
alloy-primitives = "1.4.1"
